NOTE_NAMES = {
    35: "Acoustic Bass Drum",
    36: "Bass Drum 1",
    37: "Side Stick",
    38: "Acoustic Snare",
    39: "Hand Clap",
    40: "Electric Snare",
    41: "Low Floor Tom",
    42: "Closed Hi-Hat",
    43: "High Floor Tom",
    44: "Pedal Hi-Hat",
    45: "Low Tom",
    46: "Open Hi-Hat",
    47: "Low-Mid Tom",
    48: "Hi-Mid Tom",
    49: "Crash Cymbal 1",
    50: "High Tom",
    51: "Ride Cymbal 1",
    52: "Chinese Cymbal",
    53: "Ride Bell",
    54: "Tambourine",
    55: "Splash Cymbal",
    56: "Cowbell",
    57: "Crash Cymbal 2",
    58: "Vibra Slap",
    59: "Ride Cymbal 2",
    60: "Hi Bongo",
    61: "Low Bongo",
    62: "Mute Hi Conga",
    63: "Open Hi Conga",
    64: "Low Conga",
    65: "High Timbale",
    66: "Low Timbale",
    67: "High Agogo",
    68: "Low Agogo",
    69: "Cabasa",
    70: "Maracas",
    71: "Short Whistle",
    72: "Long Whistle",
    73: "Short Guiro",
    74: "Long Guiro",
    75: "Claves",
    76: "Hi Wood Block",
    77: "Low Wood Block",
    78: "Mute Cuica",
    79: "Open Cuica",
    80: "Mute Triangle",
    81: "Open Triangle"
}

MUSICAL_SYMBOLS = {
    "♩": "Quarter Note",
    "♪": "Eighth Note",
    "♫": "Beamed Eighth Notes / Multiple Eighth Notes",
    "♬": "Beamed Sixteenth Notes",
    "𝅝": "Whole Note",
    "𝅗𝅥": "Half Note",
    "𝅘𝅥": "Quarter Note (Unicode Standard)",
    "𝅘𝅥𝅮": "Eighth Note (Unicode Standard)",
    "𝅘𝅥𝅯": "Sixteenth Note",
    "𝅘𝅥𝅰": "Thirty-second Note",

    "𝄽": "Whole Rest",
    "𝄼": "Half Rest",
    "𝄻": "Quarter Rest",
    "𝄾": "Eighth Rest",
    "𝄿": "Sixteenth Rest",

    "𝄞": "Treble Clef",
    "𝄢": "Bass Clef",
    "𝄡": "Percussion Clef",   # Used for drums
    "𝄟": "C Clef (Alto/Tenor)",

    "𝄐": "Fermata (Hold the note)",
    "𝄁": "Double Barline",
    "𝄂": "Final Barline",
    "𝄃": "Reverse Final Barline",
    "𝄀": "Single Barline",

    "𝄅": "Repeat Start",
    "𝄆": "Repeat End",

    ">": "Accent",
    "^": "Marcato Accent",
    "-": "Tenuto (Play smoothly / connected)",
    ".": "Staccato (Short note)",

    "𝆑": "Crescendo",
    "𝆓": "Decrescendo / Diminuendo",
    "p": "Piano (Soft)",
    "pp": "Pianissimo (Very Soft)",
    "f": "Forte (Loud)",
    "ff": "Fortissimo (Very Loud)",
    "mf": "Mezzo Forte (Medium Loud)",
    "mp": "Mezzo Piano (Medium Soft)",

    "𝄋": "Coda",
    "𝄌": "Segno",
    "D.C.": "Da Capo (Go to beginning)",
    "D.S.": "Dal Segno (Go to sign)",
    "Fine": "End",
    "To Coda": "Jump to Coda",

    "O": "Open Hi-Hat / Open Sound (Drum notation)",
    "+": "Closed Hi-Hat",
    "x": "Cymbal Notehead",
    "o": "Ghost Note",
}
